### ISSUE TITLE
Create restaurang tags

### ISSUE THREAD

**Issue by sseagull** [megdadkins7/restaurant-picker#3]
Currently each restaurant node simply lists out the type it is (ramen, mexican..) along with its type 'Dine-in / take-out' and its drink options. To help a user visually parse the `takeout` and `drinks` status, lets make tags for these and give each tag a unique color.

## Todo

- [ ] Create the following tags: `takeOut`, `dineIn`, `cocktails`, `beer`
- [ ] Give each tag an associated color
- [ ] (optional) you might want to give each tag a 'displayName' that you use to print out the label
- [ ] Swap the tags into the restaurant nodes - **If there is no tags for a node, don't show anything.**

Tags can look something like this (taken from discord) - entirely up to you in terms of design:

<img width="253" alt="Screen Shot 2020-11-17 at 3 15 14 PM" src="https://user-images.githubusercontent.com/54673844/99444079-b5f2a080-28e9-11eb-9b1e-8020517dbc4e.png">

**Comment by megdadkins7** [comment]
location and alcohol type style tags added
